# Generated by Django 3.2.10 on 2021-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_acidity', models.FloatField(verbose_name='fixed acidity')),
                ('volatile_acidity', models.FloatField(verbose_name='volatile acidity')),
                ('citric_acid', models.FloatField(verbose_name='citric acid')),
                ('residual_sugar', models.FloatField(verbose_name='residual sugar')),
                ('chlorides', models.FloatField(verbose_name='chlorides')),
                ('free_sulfur', models.FloatField(verbose_name='free sulfur')),
                ('total_sulfur', models.FloatField(verbose_name='total sulfur')),
                ('density', models.FloatField(verbose_name='density')),
                ('pH', models.FloatField(verbose_name='pH')),
                ('sulphates', models.FloatField(verbose_name='sulphates')),
                ('alcohol', models.FloatField(verbose_name='alcohol')),
                ('quality', models.FloatField(verbose_name='quality')),
            ],
        ),
    ]
